### ISSUE TITLE
.releaset is in project root directory, not able to support monorepo

### ISSUE THREAD

**Issue by AlfredChow2338** [AlfredChow2338/releaset#2]
Since the `publish_note.json` and `info.json` are stored in the project root directory, if the projects runs multiple projects or uses monorepo, the information will be conflicted. Therefore I suggest to put `.releaset` folder inside `outDir` path such that different output directory can have their own .releaset folder to store the information such as last updated tag date time and publish note. This will be more flexible.

**Comment by bms-alfred-chow** [comment]
Issue closed by release of v0.1.5: https://github.com/AlfredChow2338/releaset/commit/0db48fc8470e7fb1fde21b06c05146eaa84c52ad
